### ISSUE TITLE
Agenda for angular-chart 0.3.0

### ISSUE THREAD

**Issue by maxklenk** [maxklenk/angular-chart#55]
Version 0.3.0 will contain some structural changes to separate functions and to be able to keep up with the development of c3.js.

## Tasks
- [x] adjust angular-chart options to c3.js configuration to allow an easier transition from c3.js to angular-chart
- [x] find a way to set/update all simple c3.js configuration parameters at once (#53, #54)
- [x] define how the schema object sets config parameters (set postfix, displayFormat, ...)
- [ ] extract in-place editor features from core file

**Comment by ulilicht** [comment]
an idea: 
Maybe start with fresh copy of the c3 config object each update run - this would make most "else" branches obsolete. Currently, most of them are used to set null values or empty strings.

**Comment by maxklenk** [comment]
@ulilicht That would definitely help, we could start with an empty object an rely on the c3.js defaults or we could set own defaults.

Before focusing on the implementation I would like to discuss the API:

# API

The options object contains four types of key:value pairs:
* dimension definition (```rows```, ```xAxis.key```)
* c3.js parameters (```size```, ```xAxis.max```)
* additional state information (```zoom.range```, ```selection.selected```)
* editor configuration (```subchart.selector```)

## Combined Access (close to current implementation)
```javascript
var options = {
  rows: [{
    key: 'income',
    type: 'bar',
    axis: 'y' // default
  }],
  axis: {
    x: {
      key: 'day',
      displayFormat: '%Y-%m-%d %H:%M:%S',
      max: 5,
      editor: true
    }
  },
  size: {
    height: 200,
    width: 200
  },
  zoom: {
    range: [2, 4]
  }
};
```
#### :+1: Advantages
* access to the same element on same places
* allows to overwrite with specific chart options

#### :-1: Disadvantages
* all c3.js configurations have to be specified
* extension for trees or maps will be messy

## Distinct Access
```javascript
var options = {
  dimensions:  {
    "income": {
      type: 'bar',
      axis: 'y' // default
    },
    'day': {
      axis: 'x',
      displayFormat: '%Y-%m-%d %H:%M:%S'
    }
  },
  chart: {
    size: {
      height: 200,
      width: 200
    },
    axis: {
      x: {
        max: 5
      }
    }
  },
  editors: {
    xAxis: true
  },
  state: {
    zoomRange: [2, 4]
  }
};
```
#### :+1: Advantages
* easy to set up watchers
* allows to overwrite with specific chart options
* allows to support infinite number of c3.js configurations
* can be easily extended with categories for trees or maps

#### :-1: Disadvantages
* access to the same element on different places (set dimension to x-axis, set x-axis min/max in chart, enable x-axis selector in editor)

@ulilicht, @sebastianhenneberg and anybody else: What advantages/disadvantages do you see, which other solutions are possible?

**Comment by ulilicht** [comment]
Hi Max, 
thanks for your comparision! 

what is the goal of angular-chart? Is it 
 - "developing a standalone chart solution for angular with a ton of great features"
or is it
 - "developing an easy to use integration layer for c3.js with some gimmicks"

For me, it seems to be the latter as reinventing the wheel does not make much sense to me here. Therefore I'd keep everything very close to the original c3.js. 

Some other points are: 
pro solution 1: 
 - there are some points where c3.js seems to be a bit complicated. e.g. formatting of data: I'd like to specify a data format on the data itself, as it normally never changes. If a value refers to money, it is formatted with a currency symbol. With solution 2 (and also current angular-chart implementation, but this could be fixed) I'd have to speficy the format on the tooltip and on the axis (and probably somewhere else). This seems to be overhead. 

pro solution 2: 
 - c3.js seems to be in rapid development, they have feature-releases more or less every 3 months. It would be a lot of work to port every feature to angular-chart. In the last 3 months, ~5k lines of code were edited. 
 - c3.js has no stable api we could rely on - version number < 1

**Comment by maxklenk** [comment]
Hey @ulilicht,

thank you for your feedback. I discussed it and where we want to go with *angular-chart* with @sebastianhenneberg. *angular-chart* does not only connect c3.js to the AngularJS data-binding, projects like [jettro/c3-angular-sample](https://github.com/jettro/c3-angular-sample) try to solve only this task so.
We want to do more, especially the formatting of the data using our schema object and the display of the different dimensions should be easier configurable. On the long run we plan to extend the library to support more chart types and perhaps even trees or other visualizations.

**Comment by maxklenk** [comment]
Furthermore I would like to break the directives code in multiple parts, which can be tested on their own and support a better overview what is happening where.

* `directive.js  - angularChart`

  Directive definition, require/export stuff

* `controller.js - angularChartController`

  Controller which initializes creation

* `service.js - angularChartService`

  Service which connects the other service

* `watcher.js - angularChartWatcher`

  Service which provides different advanced watch functions

* `converter.js - angularChartConverter`

  Service which translates the dimensions/schema into a c3 
configuration

* `state.js - angularChartState`

  Service responsible to sync the state with chart events

* `editors.js - angularChartEditors`

  Wraps the editors
